import React from "react";

function CategoryCard() {
    //Initialize all Categories and Hover Elements
    const allCategories = [
        "A Boy's Name",
        "U.S. Cities",
        "Things That Are Cold",
        "School Supplies",
        "Pro Sports Teams",
        "Insects",
        "Breakfast Foods",
        "T.V. Shows",
        "Things That Are Found in the Ocean",
        "Presidents",
        "Product Names",
        "Appliances",
        "Types of Drink",
        "Personality Traits",
        "Articles of Clothing",
        "Desserts",
        "Car Parts",
        "Things Found on a Map",
        "Athletes",
        "4-Letter Words",
        "Items in a Refrigerator",
        "Farm Animals",
        "Street Names",
        "Things on a Beach",
        "Colors",
        "Tools",
        "A Girl's Name",
        "Villains/Monsters",
        "Footwear",
        "Something You're Afraid Of",
        "Terms of Measurement",
        "Book Titles",
        "Heroes",
        "Gifts/Presents",
        "Kinds of Dances",
        "Things That Are Black",
        "Vehicles",
        "Tropical Locations",
        "College Majors",
        "Dairy Products",
        "Things in a Souvenir Shop",
        "Items in Your Purse/Wallet",
        "Famous Females",
        "Medicine/Drugs",
        "Things Made of Metal",
        "People in Uniform",
        "Things You Plug In",
        "Animals",
        "Languages",
        "Names Used in the Bible",
        "Junk Food",
        "Things That Grow",
        "Companies",
        "Video Games",
        "Electronic Gadgets",
        "Board Games",
        "Things That Use a Remote",
        "Card Games",
        "Internet Lingo",
        "Offensive Words",
        "Wireless Things",
        "Computer Parts",
        "Software",
        "Websites",
        "Game Terms",
        "Things in a Grocery Store",
        "Reasons to Quit Your Job",
        "Things That Have Stripes",
        "Tourist Attractions",
        "Diet Foods",
        "Things Found in a Hospital",
        "Food/Drink That Is Green",
        "Weekend Activities",
        "Seafood",
        "Christmas Songs",
        "Words Ending in -N",
        "Words With Double Letters",
        "Children's Books",
        "Things Found at a Bar",
        "Sports Played Indoors",
        "Names Used in Songs",
        "Foods You Eat Raw",
        "Places in Europe",
        "Olympic Events",
        "Things You See at the Zoo",
        "Animals in Books or Movies",
        "Things to Do at a Party",
        "Kinds of Soup",
        "Things Found in New York",
        "Things You Get Tickets For",
        "Things You Do at Work",
        "Foreign Words Used in English",
        "Things You Shouldn't Touch",
        "Spicy Foods",
        "Things at a Carnival",
        "Things You Make",
        "Places to Hang Out",
        "Honeymoon Spots",
        "Things You Buy for Kids",
        "Reasons to Take Out a Loan",
        "Things to Do on a Date",
        "Historic Events",
        "Things You Do Every Day",
        "Things You Save Up to Buy",
        "Things You Sit On",
        "Reasons to Make a Phone Call",
        "Types of Weather",
        "Titles People Can Have",
        "Things That Have Buttons",
        "Items You Take On a Trip",
        "Things That Have Wheels",
        "Reasons to Call 911",
        "Things That Make You Smile",
        "Ways to Kill Time",
        "Hobbies",
        "Holiday Activities",
        "European Capitals",
    ];
    

    return <div>CategoryCard</div>;
}

export default CategoryCard;
